testquery_data = [{"director": "",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": ""},
                  {"director": "Ron Howard",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": ""},
                  {"director": "Ron Howard",
                   "writer": "Dan Brown",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": ""},
                  {"director": "Ron Howard",
                   "writer": "Dan Brown",
                   "year_from": 2000,
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": ""},
                  {"director": "Ron Howard",
                   "writer": "Dan Brown",
                   "year_from": 2000,
                   "year_to": 2018,
                   "genres": "",
                   "minRatingIMDB": ""},
                  {"director": "Ron Howard",
                   "writer": "Dan Brown",
                   "year_from": 2000,
                   "year_to": 2018,
                   "genres": "Action",
                   "minRatingIMDB": ""},
                  {"director": "Ron Howard",
                   "writer": "Dan Brown",
                   "year_from": 2000,
                   "year_to": 2018,
                   "genres": "Action,Adventure",
                   "minRatingIMDB": ""},
                  {"director": "Ron Howard",
                   "writer": "Dan Brown",
                   "year_from": 2000,
                   "year_to": 2018,
                   "genres": "Action,Adventure",
                   "minRatingIMDB": 5.0},
                  ]
