testquery_data = [{"title": "dummyquery",
                   "director": "dummyquery",
                   "writer": "dummyquery",
                   "year_from": "dummyquery",
                   "year_to": "dummyquery",
                   "genres": "dummyquery",
                   "min_rating_imdb": "dummyquery",
                   "principals": "dummyquery"},
                  {"title": "",
                   "director": "",
                   "writer": "",
                   "year_from": "2016",
                   "year_to": "2016",
                   "genres": ["Comedy"],
                   "min_rating_imdb": "",
                   "principals": ""},
                  {"title": "",
                   "director": "Ron Howard",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ""},
                  {"title": "",
                   "director": "Ron Howard",
                   "writer": "Dan Brown",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ""},
                  {"title": "",
                   "director": "Ron Howard",
                   "writer": "",
                   "year_from": 2000,
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ""},
                  {"title": "",
                   "director": "Ron Howard",
                   "writer": "",
                   "year_from": '',
                   "year_to": 2018,
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ""},
                  {"title": "",
                   "director": "Ron Howard",
                   "writer": "",
                   "year_from": '',
                   "year_to": '',
                   "genres": "Action",
                   "min_rating_imdb": "",
                   "principals": ""},
                  {"title": "",
                   "director": "Ron Howard",
                   "writer": "",
                   "year_from": '',
                   "year_to": '',
                   "genres": ["Action", "Adventure"],
                   "min_rating_imdb": "",
                   "principals": ""},
                  {"title": "",
                   "director": "Ron Howard",
                   "writer": "",
                   "year_from": '',
                   "year_to": '',
                   "genres": '',
                   "min_rating_imdb": 5.0,
                   "principals": ""},
                  {"title": "",
                   "director": "",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ["Harvey Keitel"]},
                  {"title": "",
                   "director": "",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ["Harvey Keitel", "Tim Roth"]},
                  {"title": "",
                   "director": "Quentin Tarantino",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ["Christoph Waltz"]},
                  {"title": "",
                   "director": "Ethan Coen",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ["Jeff Bridges"]},
                  {"title": "Little Miss Sunshine",
                   "director": "",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ["", "", ""]},
                  {"title": "iss sunsh",
                   "director": "",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "min_rating_imdb": "",
                   "principals": ["", "", ""]},

                  ]
