testquery_data = [{"director": "dummyquery",
                   "writer": "dummyquery",
                   "year_from": "dummyquery",
                   "year_to": "dummyquery",
                   "genres": "dummyquery",
                   "minRatingIMDB": "dummyquery",
                   "principals": "dummyquery"},
                  {"director": "",
                   "writer": "",
                   "year_from": "2016",
                   "year_to": "2016",
                   "genres": ["Comedy"],
                   "minRatingIMDB": "",
                   "principals": ""},
                  {"director": "Ron Howard",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": "",
                   "principals": ""},
                  {"director": "Ron Howard",
                   "writer": "Dan Brown",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": "",
                   "principals": ""},
                  {"director": "Ron Howard",
                   "writer": "",
                   "year_from": 2000,
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": "",
                   "principals": ""},
                  {"director": "Ron Howard",
                   "writer": "",
                   "year_from": '',
                   "year_to": 2018,
                   "genres": "",
                   "minRatingIMDB": "",
                   "principals": ""},
                  {"director": "Ron Howard",
                   "writer": "",
                   "year_from": '',
                   "year_to": '',
                   "genres": "Action",
                   "minRatingIMDB": "",
                   "principals": ""},
                  {"director": "Ron Howard",
                   "writer": "",
                   "year_from": '',
                   "year_to": '',
                   "genres": ["Action", "Adventure"],
                   "minRatingIMDB": "",
                   "principals": ""},
                  {"director": "Ron Howard",
                   "writer": "",
                   "year_from": '',
                   "year_to": '',
                   "genres": '',
                   "minRatingIMDB": 5.0,
                   "principals": ""},
                  {"director": "",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": "",
                   "principals": ["Harvey Keitel"]},
                  {"director": "",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": "",
                   "principals": ["Harvey Keitel", "Tim Roth"]},
                  {"director": "Quentin Tarantino",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": "",
                   "principals": ["Christoph Waltz"]},
                  {"director": "Ethan Coen",
                   "writer": "",
                   "year_from": "",
                   "year_to": "",
                   "genres": "",
                   "minRatingIMDB": "",
                   "principals": ["Jeff Bridges"]}
                  ]
